#!/bin/bash
set -x

if nubis-metadata NUBIS_ARENA > /dev/null 2>&1; then
    NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
    find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%ARENA%%/$NUBIS_ARENA/g"
fi

if nubis-metadata NUBIS_ENVIRONMENT > /dev/null 2>&1;  then
  NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%ENVIRONMENT%%/$NUBIS_ENVIRONMENT/g"
fi

if nubis-metadata NUBIS_STACK > /dev/null 2>&1; then
  NUBIS_STACK=$(nubis-metadata NUBIS_STACK)
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%STACK%%/$NUBIS_STACK/g"
fi

if nubis-metadata NUBIS_PROJECT > /dev/null 2>&1; then
  NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%PROJECT%%/$NUBIS_PROJECT/g"
fi

if nubis-metadata NUBIS_PURPOSE > /dev/null 2>&1; then
  NUBIS_PURPOSE=$(nubis-metadata NUBIS_PURPOSE)
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%PURPOSE%%/$NUBIS_PURPOSE/g"
fi

systemctl restart confd
