#!/bin/bash
set -x

NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)
NUBIS_STACK=$(nubis-metadata NUBIS_STACK)
NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
NUBIS_PURPOSE=$(nubis-metadata NUBIS_PURPOSE)

if [ "$NUBIS_ARENA" != "" ]; then
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%ARENA%%/$NUBIS_ARENA/g"
fi

if [ "$NUBIS_ENVIRONMENT" != "" ]; then
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%ENVIRONMENT%%/$NUBIS_ENVIRONMENT/g"
fi

if [ "$NUBIS_STACK" != "" ]; then
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%STACK%%/$NUBIS_STACK/g"
fi

if [ "$NUBIS_PROJECT" != "" ]; then
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%PROJECT%%/$NUBIS_PROJECT/g"
fi

if [ "$NUBIS_PURPOSE" != "" ]; then
  find /etc/confd/conf.d -type f -print0 -name '*.toml' | xargs -0 --verbose sed -i -e "s/%%PURPOSE%%/$NUBIS_PURPOSE/g"
fi

systemctl restart confd
